import { TMinusMilestone } from '../types';

export type WhatsAppSessionStatus = 
  | 'OUTREACH_SENT'                   // Template sent, waiting for user quick reply or message
  | 'WAITING_FOR_DETAILS'            // User clicked "Add Details", waiting for text response
  | 'MILESTONES_PENDING_CONFIRMATION'// Gemini generated milestones, awaiting user confirmation
  | 'CONFIRMED_SYNCED'               // Milestones pushed to Google Calendar
  | 'TRACKED_AS_IS'                  // User clicked "Track As-Is" (baseline milestones applied)
  | 'IGNORED'                        // User clicked "Ignore"
  | 'EXPIRED';                       // 24-hour Meta window expired without reply

export interface WhatsAppTranscriptMessage {
  id: string;
  sender: 'user' | 'bot' | 'system';
  text: string;
  timestamp: string;
  type?: 'template' | 'text' | 'interactive_buttons' | 'button_reply';
  buttonPayload?: string;
}

export interface WhatsAppEventContext {
  partySize?: number;
  isTrip?: boolean;
  destination?: string;
  subActivities?: string[];
  dietaryOrDining?: string;
  giftNeeded?: boolean;
  userRawNotes?: string;
  extractedKeyDetails?: string[];
}

/**
 * Event-Context State Schema
 * Stored in database/session store while waiting for WhatsApp user response
 */
export interface WhatsAppEventSessionState {
  sessionId: string;                      // e.g. "wa-sess-14155552671-evt-123"
  phoneNumber: string;                    // Recipient E.164 phone number
  userFirstName: string;                  // {{1}} in template
  eventId: string;                        // Local AheadOfTime event ID
  googleCalendarEventId?: string;         // Google Calendar ID if imported from Google
  eventTitle: string;                     // {{2}} in template
  eventDate: string;                      // YYYY-MM-DD ({{3}} in template)
  eventTime?: string;                     // HH:mm
  eventLocation?: string;
  status: WhatsAppSessionStatus;
  
  // Timing & Meta 24-hour conversational window
  createdAt: string;                      // ISO timestamp when proactive outreach was sent
  lastInteractionAt: string;              // ISO timestamp of last inbound or outbound message
  sessionExpiresAt: string;               // ISO timestamp (createdAt + 24 hours)
  
  // Conversation history
  messagesTranscript: WhatsAppTranscriptMessage[];
  
  // Extracted context from user conversational answers
  gatheredContext: WhatsAppEventContext;
  
  // Milestones generated by Gemini
  generatedMilestones?: TMinusMilestone[];
  conversationalSummary?: string;
  
  // Google Calendar writeback status
  syncedToGoogleAt?: string;
  googleSyncedMilestoneIds?: string[];
  
  // Extensibility metadata
  metadata?: Record<string, any>;
}

/**
 * Meta WhatsApp Cloud API Outbound Proactive Template Request Payload
 */
export interface MetaTemplateMessagePayload {
  messaging_product: 'whatsapp';
  recipient_type: 'individual';
  to: string;
  type: 'template';
  template: {
    name: string;
    language: {
      code: string;
    };
    components: Array<{
      type: 'header' | 'body' | 'button';
      sub_type?: 'quick_reply' | 'url';
      index?: string | number;
      parameters: Array<{
        type: 'text' | 'payload';
        text?: string;
        payload?: string;
      }>;
    }>;
  };
}

/**
 * Meta WhatsApp Interactive Quick-Reply Buttons Payload (Within 24h window)
 */
export interface MetaInteractiveButtonsPayload {
  messaging_product: 'whatsapp';
  recipient_type: 'individual';
  to: string;
  type: 'interactive';
  interactive: {
    type: 'button';
    body: {
      text: string;
    };
    action: {
      buttons: Array<{
        type: 'reply';
        reply: {
          id: string;
          title: string;
        };
      }>;
    };
  };
}

/**
 * Meta WhatsApp Plain Text Message Payload
 */
export interface MetaTextMessagePayload {
  messaging_product: 'whatsapp';
  recipient_type: 'individual';
  to: string;
  type: 'text';
  text: {
    preview_url?: boolean;
    body: string;
  };
}

/**
 * Incoming Meta WhatsApp Webhook Payload Structure
 */
export interface MetaWebhookPayload {
  object: string;
  entry: Array<{
    id: string;
    changes: Array<{
      field: string;
      value: {
        messaging_product: string;
        metadata: {
          display_phone_number: string;
          phone_number_id: string;
        };
        contacts?: Array<{
          profile: {
            name: string;
          };
          wa_id: string;
        }>;
        messages?: Array<{
          from: string;
          id: string;
          timestamp: string;
          type: 'text' | 'button' | 'interactive' | 'audio';
          text?: {
            body: string;
          };
          button?: {
            text: string;
            payload: string;
          };
          interactive?: {
            type: 'button_reply';
            button_reply: {
              id: string;
              title: string;
            };
          };
        }>;
        statuses?: Array<{
          id: string;
          status: 'sent' | 'delivered' | 'read' | 'failed';
          timestamp: string;
          recipient_id: string;
        }>;
      };
    }>;
  }>;
}
